# Generated by Django 5.1.4 on 2025-01-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
